/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 02-апр-2025 0:33:04 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW VIEW_A
;

/* Drop Tables */

DROP TABLE "Crops "
;

DROP TABLE "Equipment "
;

DROP TABLE "FertilizationHistory "
;

DROP TABLE "FertilizationPlans "
;

DROP TABLE "Fertilizers "
;

DROP TABLE "FieldAnalyses "
;

DROP TABLE "Fields "
;

DROP TABLE SoilTypes
;

DROP TABLE TABLE_A
;

DROP TABLE TABLE_B
;

DROP TABLE TABLE_C
;

DROP TABLE "Users "
;

DROP TABLE "WeatherConditions "
;

/* Create Tables */

CREATE TABLE "Crops "
(
	Id_crops INTEGER NOT NULL,
	Name VARCHAR(10) NULL,
	ScientificName VARCHAR(10) NULL,
	GrowingSeason VARCHAR(10) NULL,
	AverageYield VARCHAR(10) NULL,
	Description VARCHAR(10) NULL
)
;

CREATE TABLE "Equipment "
(
	Equipment_Id INTEGER NOT NULL,
	Name VARCHAR(10) NULL,
	Type VARCHAR(10) NULL,
	Model VARCHAR(10) NULL,
	SerialNumber INTEGER NULL,
	Status VARCHAR(10) NULL,
	PurchasePrice DECIMAL(5) NULL,
	PurchaseDate DATE NULL,
	Description VARCHAR(10) NULL
)
;

CREATE TABLE "FertilizationHistory "
(
	FertilizationHistory_Id INTEGER NOT NULL,
	ApplicationDate DATE NULL,
	ApplicationMethod VARCHAR(10) NULL,
	Amount INTEGER NULL,
	Notes INTEGER NULL,
	Id_field INTEGER NULL,
	Fertilizers_Id INTEGER NULL,
	Id_crops INTEGER NULL
)
;

CREATE TABLE "FertilizationPlans "
(
	FertilizationPlans_Id INTEGER NOT NULL,
	ApplicationMethod VARCHAR(10) NULL,
	Amount INTEGER NULL,
	PlannedDate DATE NULL,
	Notes INTEGER NULL,
	Fertilizers_Id INTEGER NULL,
	Id_field INTEGER NULL,
	Id_user INTEGER NULL,
	Equipment_Id INTEGER NULL
)
;

CREATE TABLE "Fertilizers "
(
	Fertilizers_Id INTEGER NOT NULL,
	Name VARCHAR(10) NULL,
	Type VARCHAR(10) NULL,
	Description VARCHAR(10) NULL,
	PricePerUnit DECIMAL(5) NULL,
	NitrogenContent INTEGER NULL,
	PhosphorusContent INTEGER NULL,
	PotassiumContent INTEGER NULL,
	Unit INTEGER NULL
)
;

CREATE TABLE "FieldAnalyses "
(
	FieldAnalyses_Id INTEGER NOT NULL,
	AnalysisDate DATE NULL,
	pH INTEGER NULL,
	OrganicMatter VARCHAR(1) NULL,
	Nitrogen INTEGER NULL,
	Phosphorus INTEGER NULL,
	Potassium INTEGER NULL,
	Notes INTEGER NULL,
	Id_field INTEGER NULL
)
;

CREATE TABLE "Fields "
(
	Id_field INTEGER NOT NULL,
	Name VARCHAR(10) NULL,
	Location VARCHAR(10) NULL,
	Area VARCHAR(10) NULL,
	Description VARCHAR(10) NULL,
	SoilType_Id INTEGER NULL
)
;

CREATE TABLE SoilTypes
(
	SoilType_Id INTEGER NOT NULL,
	Name VARCHAR(10) NULL,
	Description VARCHAR(10) NULL,
	pH INTEGER NULL,
	OrganicMatter VARCHAR(1) NULL,
	ClayContent INTEGER NULL,
	SiltContent INTEGER NULL,
	SandContent INTEGER NULL
)
;

CREATE TABLE TABLE_A
(
	ID INTEGER NOT NULL,
	COLUMN_A INTEGER NULL,
	"COLUMN B" INTEGER NULL
)
;

CREATE TABLE TABLE_B
(
	COLUMN_A INTEGER NULL,
	"COLUMN B" INTEGER NULL
)
;

CREATE TABLE TABLE_C
(
	COLUMN_A INTEGER NULL,
	"COLUMN B" INTEGER NULL
)
;

CREATE TABLE "Users "
(
	Id_user INTEGER NOT NULL,
	Username VARCHAR(10) NULL,
	Email VARCHAR(10) NULL,
	FirstName VARCHAR(10) NULL,
	LastName VARCHAR(10) NULL,
	PasswordHash VARCHAR(10) NULL,
	Role VARCHAR(10) NULL
)
;

CREATE TABLE "WeatherConditions "
(
	WeatherConditions_Id INTEGER NOT NULL,
	Date DATE NULL,
	Temperature INTEGER NULL,
	Humidity VARCHAR(10) NULL,
	Precipitation VARCHAR(10) NULL,
	WindSpeed DOUBLE NULL,
	Description VARCHAR(10) NULL,
	Id_field INTEGER NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Crops " ADD CONSTRAINT "PK_Crops "
	PRIMARY KEY (Id_crops)
;

ALTER TABLE "Equipment " ADD CONSTRAINT "PK_Equipment "
	PRIMARY KEY (Equipment_Id)
;

ALTER TABLE "FertilizationHistory " ADD CONSTRAINT "PK_FertilizationHistory "
	PRIMARY KEY (FertilizationHistory_Id)
;

CREATE INDEX "IXFK_FertilizationHistory _Crops " ON "FertilizationHistory " (Id_crops ASC)
;

CREATE INDEX "IXFK_FertilizationHistory _Fertilizers " ON "FertilizationHistory " (Fertilizers_Id ASC)
;

CREATE INDEX "IXFK_FertilizationHistory _Fields " ON "FertilizationHistory " (Id_field ASC)
;

ALTER TABLE "FertilizationPlans " ADD CONSTRAINT "PK_FertilizationPlans "
	PRIMARY KEY (FertilizationPlans_Id)
;

CREATE INDEX "IXFK_FertilizationPlans _Equipment " ON "FertilizationPlans " (Equipment_Id ASC)
;

CREATE INDEX "IXFK_FertilizationPlans _Fertilizers " ON "FertilizationPlans " (Fertilizers_Id ASC)
;

CREATE INDEX "IXFK_FertilizationPlans _Fields " ON "FertilizationPlans " (Id_field ASC)
;

CREATE INDEX "IXFK_FertilizationPlans _Users " ON "FertilizationPlans " (Id_user ASC)
;

ALTER TABLE "Fertilizers " ADD CONSTRAINT "PK_Fertilizers "
	PRIMARY KEY (Fertilizers_Id)
;

ALTER TABLE "FieldAnalyses " ADD CONSTRAINT "PK_FieldAnalyses "
	PRIMARY KEY (FieldAnalyses_Id)
;

CREATE INDEX "IXFK_FieldAnalyses _Fields " ON "FieldAnalyses " (Id_field ASC)
;

ALTER TABLE "Fields " ADD CONSTRAINT "PK_Fields "
	PRIMARY KEY (Id_field)
;

CREATE INDEX "IXFK_Fields _SoilTypes" ON "Fields " (SoilType_Id ASC)
;

ALTER TABLE SoilTypes ADD CONSTRAINT PK_SoilTypes
	PRIMARY KEY (SoilType_Id)
;

ALTER TABLE TABLE_A ADD CONSTRAINT "PK_Table A"
	PRIMARY KEY (ID)
;

ALTER TABLE "Users " ADD CONSTRAINT "PK_Users "
	PRIMARY KEY (Id_user)
;

ALTER TABLE "WeatherConditions " ADD CONSTRAINT "PK_WeatherConditions "
	PRIMARY KEY (WeatherConditions_Id)
;

CREATE INDEX "IXFK_WeatherConditions _Fields " ON "WeatherConditions " (Id_field ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "FertilizationHistory " ADD CONSTRAINT "FK_FertilizationHistory _Crops "
	FOREIGN KEY (Id_crops) REFERENCES "Crops " (Id_crops) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FertilizationHistory " ADD CONSTRAINT "FK_FertilizationHistory _Fertilizers "
	FOREIGN KEY (Fertilizers_Id) REFERENCES "Fertilizers " (Fertilizers_Id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FertilizationHistory " ADD CONSTRAINT "FK_FertilizationHistory _Fields "
	FOREIGN KEY (Id_field) REFERENCES "Fields " (Id_field) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FertilizationPlans " ADD CONSTRAINT "FK_FertilizationPlans _Equipment "
	FOREIGN KEY (Equipment_Id) REFERENCES "Equipment " (Equipment_Id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FertilizationPlans " ADD CONSTRAINT "FK_FertilizationPlans _Fertilizers "
	FOREIGN KEY (Fertilizers_Id) REFERENCES "Fertilizers " (Fertilizers_Id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FertilizationPlans " ADD CONSTRAINT "FK_FertilizationPlans _Fields "
	FOREIGN KEY (Id_field) REFERENCES "Fields " (Id_field) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FertilizationPlans " ADD CONSTRAINT "FK_FertilizationPlans _Users "
	FOREIGN KEY (Id_user) REFERENCES "Users " (Id_user) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "FieldAnalyses " ADD CONSTRAINT "FK_FieldAnalyses _Fields "
	FOREIGN KEY (Id_field) REFERENCES "Fields " (Id_field) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Fields " ADD CONSTRAINT "FK_Fields _SoilTypes"
	FOREIGN KEY (SoilType_Id) REFERENCES SoilTypes (SoilType_Id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE TABLE_B ADD CONSTRAINT FK_TABLE_B_TABLE_A
	FOREIGN KEY (COLUMN_A) REFERENCES TABLE_A (ID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE TABLE_C ADD CONSTRAINT FK_TABLE_C_TABLE_A
	FOREIGN KEY (COLUMN_A) REFERENCES TABLE_A (ID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "WeatherConditions " ADD CONSTRAINT "FK_WeatherConditions _Fields "
	FOREIGN KEY (Id_field) REFERENCES "Fields " (Id_field) ON DELETE No Action ON UPDATE No Action
;

/* Create Views */

CREATE VIEW VIEW_A AS 
/* SQL statements defining VIEW_A */
;

COMMENT ON TABLE VIEW_A
	IS '[Business description of the purpose of the view.]'
;
