// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.AppDbContext;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250416202145_AddSeasonsData")]
    partial class AddSeasonsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentTasks", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("EquipmentTasks");
                });

            modelBuilder.Entity("PlantingPlansTasks", b =>
                {
                    b.Property<Guid>("PlantingPlansId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid");

                    b.HasKey("PlantingPlansId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("PlantingPlansTasks");
                });

            modelBuilder.Entity("TasksWorkers", b =>
                {
                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkersId")
                        .HasColumnType("uuid");

                    b.HasKey("TasksId", "WorkersId");

                    b.HasIndex("WorkersId");

                    b.ToTable("TasksWorkers");
                });

            modelBuilder.Entity("server.Models.Crops", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Growth_period")
                        .HasColumnType("integer");

                    b.Property<double>("Optimal_temperature")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Water_requirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("server.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("server.Models.FertilizationPlans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Application_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Fertilization_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Plan_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Fertilization_Id");

                    b.HasIndex("Plan_Id");

                    b.ToTable("FertilizationPlans");
                });

            modelBuilder.Entity("server.Models.Fertilizers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fertilizers");
                });

            modelBuilder.Entity("server.Models.Fields", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soil_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("server.Models.HarvestLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Actual_yield")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Harvest_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Plan_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Quality_rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Plan_Id")
                        .IsUnique();

                    b.ToTable("HarvestLogs");
                });

            modelBuilder.Entity("server.Models.PlantingPlans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Crop_id")
                        .HasColumnType("uuid");

                    b.Property<double>("Expected_yield")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Field_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Planned_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Season_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Crop_id");

                    b.HasIndex("Field_id");

                    b.HasIndex("Season_id");

                    b.ToTable("PlantingPlans");
                });

            modelBuilder.Entity("server.Models.Seasons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("server.Models.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("server.Models.Workers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("EquipmentTasks", b =>
                {
                    b.HasOne("server.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantingPlansTasks", b =>
                {
                    b.HasOne("server.Models.PlantingPlans", null)
                        .WithMany()
                        .HasForeignKey("PlantingPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TasksWorkers", b =>
                {
                    b.HasOne("server.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Workers", null)
                        .WithMany()
                        .HasForeignKey("WorkersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.FertilizationPlans", b =>
                {
                    b.HasOne("server.Models.Fertilizers", "Fertilizers")
                        .WithMany("FertilizationPlans")
                        .HasForeignKey("Fertilization_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.PlantingPlans", "PlantingPlans")
                        .WithMany("FertilizationPlans")
                        .HasForeignKey("Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fertilizers");

                    b.Navigation("PlantingPlans");
                });

            modelBuilder.Entity("server.Models.HarvestLogs", b =>
                {
                    b.HasOne("server.Models.PlantingPlans", "PlantingPlans")
                        .WithOne("HarvestLogs")
                        .HasForeignKey("server.Models.HarvestLogs", "Plan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingPlans");
                });

            modelBuilder.Entity("server.Models.PlantingPlans", b =>
                {
                    b.HasOne("server.Models.Crops", "Crops")
                        .WithMany("PlantingPlans")
                        .HasForeignKey("Crop_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Fields", "Fields")
                        .WithMany("PlantingPlans")
                        .HasForeignKey("Field_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Seasons", "Seasons")
                        .WithMany("PlantingPlans")
                        .HasForeignKey("Season_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crops");

                    b.Navigation("Fields");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("server.Models.Crops", b =>
                {
                    b.Navigation("PlantingPlans");
                });

            modelBuilder.Entity("server.Models.Fertilizers", b =>
                {
                    b.Navigation("FertilizationPlans");
                });

            modelBuilder.Entity("server.Models.Fields", b =>
                {
                    b.Navigation("PlantingPlans");
                });

            modelBuilder.Entity("server.Models.PlantingPlans", b =>
                {
                    b.Navigation("FertilizationPlans");

                    b.Navigation("HarvestLogs");
                });

            modelBuilder.Entity("server.Models.Seasons", b =>
                {
                    b.Navigation("PlantingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
